### ISSUE TITLE
Show Task List

### ISSUE THREAD

**Issue by raihanalmenata** [raihanalmenata/kitameraki_recruitment_MuhammadRaihanAlmenata#7]
### User Stories
As a **User**,
I would like to **view the list of my task**,
So that **I can keep track of all of the task on the list**

### Acceptance Criteria

- [x] Implement a card list that store cards representing user tasks.
- [x] A card consist all of the information within a task.
- [x] Create RESTful API endpoints to handle the operation.
- [x] Use appropriate HTTP methods and status codes for the operation.
